name: red_white
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#-----------------packeges------------------#
dependencies:
  flutter:
    sdk: flutter


# utility packages
  image_picker: ^1.1.1
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^3.1.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
# Icons

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8


#------------------state management--------------------#


  get: ^4.6.5
  get_storage: ^2.1.1

# Product Specific

  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1
  

# -----------------package end-----------------#


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true



  #--------------local assets----------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/animation/
    - assets/images/onboarding/
    - assets/images/banner/
    - assets/images/products/
  #--------------local fonts------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
        - asset: assets\fonts\Poppins-BlackItalic.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-BoldItalic.ttf
        - asset: assets\fonts\Poppins-ExtraBold.ttf
        - asset: assets\fonts\Poppins-ExtraBoldItalic.ttf
        - asset: assets\fonts\Poppins-ExtraLight.ttf
        - asset: assets\fonts\Poppins-ExtraLightItalic.ttf
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-LightItalic.ttf
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
        - asset: assets\fonts\Poppins-Thin.ttf
        - asset: assets\fonts\Poppins-ThinItalic.ttf

